### ISSUE TITLE
gotron-builder failed with --win, on mac

### ISSUE THREAD

**Issue by forepick** [Equanox/gotron#34]
Hi

Working on MacBook pro. 
Both `go build` and `gotron-builder` work properly for the same platform.
Cross-compiling the go app with `go build` (GOOS=windows etc...) works.

`gotron-builder --win` fails with the following error:

```
github.com/develar/app-builder/pkg/util.Execute
	/Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:92
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.12/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12/libexec/src/runtime/asm_amd64.s:1337

Error: /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.signAndEditResources (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.doBuild (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/pearl/go/src/fotomaster.com/mosaicpresentation/.gotron-builder/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
```

What do I miss?

Thanks

**Comment by puengel** [comment]
Hi,
is this the full log?
Thanks

**Comment by forepick** [comment]
Hi

Nope. 
Here, this is the **full** log after running `sudo gotron-builder --win` from the project folder:

```
npm WARN saveError ENOENT: no such file or directory, open '/Users/user/go/src/domain.com/productpackage/.gotron-builder/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/user/go/src/domain.com/productpackage/.gotron-builder/package.json'
npm WARN .gotron-builder No description
npm WARN .gotron-builder No repository field.
npm WARN .gotron-builder No README data
npm WARN .gotron-builder No license field.

+ electron-builder@20.39.0
added 197 packages in 6.869s
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • description is missed in the package.json appPackageFile=/Users/user/go/src/domain.com/productpackage/.gotron/package.json
  • author is missed in the package.json appPackageFile=/Users/user/go/src/domain.com/productpackage/.gotron/package.json
  • writing effective config file=/Users/user/go/src/domain.com/productpackage/.gotron/dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=2.0.17 appOutDir=/Users/user/go/src/domain.com/productpackage/.gotron/dist/win-unpacked
  • default Electron icon is used reason=application icon is not set
  ⨯ error: exit status 1
path: /Users/user/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine
args: /Users/user/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine /Users/user/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.4.0/rcedit-ia32.exe /Users/user/go/src/domain.com/productpackage/.gotron/dist/win-unpacked/gotron-browser-window.exe --set-version-string FileDescription gotron-browser-window --set-version-string ProductName gotron-browser-window --set-version-string LegalCopyright Copyright © 2019 gotron-browser-window --set-file-version 0.1.0 --set-product-version 0.1.0.0 --set-version-string InternalName gotron-browser-window --set-version-string OriginalFilename
output:
error output:wine: failed to initialize: dlopen(/tmp/wine-stage/wine/usr/lib/wine/ntdll.dll.so, 258): image not found

github.com/develar/app-builder/pkg/util.Execute
	/Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:92
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.12/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12/libexec/src/runtime/asm_amd64.s:1337

Error: /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.signAndEditResources (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.doBuild (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/user/go/src/domain.com/productpackage/.gotron-builder/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
1553614488 FTL home/equa/repos/gotron/cmd/gotron-builder/main.go:64 > : : exit status 1: exit status 1: : exit status 1: exit status 1
```

**Comment by puengel** [comment]
Are you using wine version 2.0?
Can you check if installing wine version 3 solves your problem?

**Comment by forepick** [comment]
I'm running wine stable 4.0 (bottled)
